/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Khofi Muffin
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        susu = new javax.swing.JButton();
        esgrim = new javax.swing.JButton();
        mochi = new javax.swing.JButton();
        waffle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 96, 60);

        susu.setText("milkshake");
        getContentPane().add(susu);
        susu.setBounds(160, 160, 120, 70);

        esgrim.setText("esgrim");
        esgrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esgrimActionPerformed(evt);
            }
        });
        getContentPane().add(esgrim);
        esgrim.setBounds(160, 90, 120, 70);

        mochi.setText("mochi");
        getContentPane().add(mochi);
        mochi.setBounds(160, 300, 120, 70);

        waffle.setText("waffle");
        getContentPane().add(waffle);
        waffle.setBounds(160, 230, 120, 70);

        setBounds(0, 0, 445, 525);
    }// </editor-fold>//GEN-END:initComponents

    private void esgrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esgrimActionPerformed
        // TODO add your handling code here:
        new eskrim().setVisible(true);
        
    }//GEN-LAST:event_esgrimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new menu().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton esgrim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mochi;
    private javax.swing.JButton susu;
    private javax.swing.JButton waffle;
    // End of variables declaration//GEN-END:variables
}
